name: Update Problem JSON

on:
  push:
    paths:
      - "problem-set-*/assets/**"  # Trigger when an image is added in any problem set folder
      - "problem-set-*/images/**"  # Trigger when a new folder is created

jobs:
  update_json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Identify Problem Set and Image
        run: |
          PROBLEM_SET=$(ls -d problem-set-* | tail -n 1)
          JSON_FILE="$PROBLEM_SET/problem.json"

          # Create JSON file if it doesn't exist
          if [ ! -f "$JSON_FILE" ]; then
            echo '{"item":[]}' > "$JSON_FILE"
          fi

          # Append new image to JSON
          IMAGE_PATH=$(ls "$PROBLEM_SET/assets" | tail -n 1)
          IMAGE_URL="https://venkatesanrpu.github.io/AI-CHEM-Gateway/$PROBLEM_SET/assets/$IMAGE_PATH"
          PROBLEM_ID=$(basename "$IMAGE_PATH" .png)

          # Add new entry to JSON
          jq --arg id "$PROBLEM_ID" --arg url "$IMAGE_URL" '.item += [{"problemID": $id, "problemImage": $url, "problemCategory": "Unknown"}]' "$JSON_FILE" > tmp.json && mv tmp.json "$JSON_FILE"

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add "$PROBLEM_SET/problem.json"
          git commit -m "Updated JSON with new image from $PROBLEM_SET"
          git push
